version: '3.8'
services:
  db:
    image: postgres:14.4
    restart: always
    environment:
      - POSTGRES_USER=candle
      - POSTGRES_PASSWORD=candle
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
